name: Model testing

on:
  push

jobs:
  training:
    runs-on: 'ubuntu-latest'


    steps:
      - name: checkout code 
        uses: actions/checkout@v5

      - name: setup python
        uses: actions/setup-python@v6
        with:
          python-version: '3.12'

      - name: install dependencies
        run: |
          pip install -r requirments.txt
      
      - name: run the test
        run: |
          python train.py
      
      - name: save the model
        uses: actions/upload-artifact@v4
        with:
          name: trained-model
          path: model/model.joblib

